---
abstract: 'to distribute test job using client and server model.'
author:
  - 'Shin Leong <lsf@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Prove-Plugin-Distributed
no_index:
  directory:
    - t
    - inc
requires:
  App::Prove: 3.23
  Carp: 0
  Cwd: 0
  Getopt::Long: 0
  IO::Select: 0
  IO::Socket::INET: 0
  Sys::Hostname: 0
  Test::More: 0
version: 0.04
