---
abstract: 'an L<App::Prove> plugin to distribute test jobs using client and server model.'
author:
  - 'Shin Leong <lsf@cpan.org>'
build_requires:
  Test::Builder: 0
  Test::Fatal: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Prove-Plugin-Distributed
no_index:
  directory:
    - t
    - inc
recommends:
  Net::Address::IP::Local: 0
  Net::Ping: 0
  PBS::Client: 0
requires:
  App::Prove: 3.22
  Carp: 0
  Config: 0
  Cwd: 0
  File::Spec: 0
  Getopt::Long: 0
  IO::File: 0
  IO::Select: 0
  IO::Socket::INET: 0
  Sys::Hostname: 0
  Test::More: 0
version: 0.08
